// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ1QXMJdTHoPGczb6AtiESeRkQQErpdwI',
    appId: '1:934588973412:web:ba2c997cf068bf31c3ba71',
    messagingSenderId: '934588973412',
    projectId: 'match-a-muslim-978ca',
    authDomain: 'match-a-muslim-978ca.firebaseapp.com',
    storageBucket: 'match-a-muslim-978ca.appspot.com',
    measurementId: 'G-JY36EQPK9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRyF5vh_j8CfaVr_DSIlGgKtB7wQBkjdo',
    appId: '1:934588973412:android:280d585e16441501c3ba71',
    messagingSenderId: '934588973412',
    projectId: 'match-a-muslim-978ca',
    storageBucket: 'match-a-muslim-978ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkcHhVVjyRA8LZc8RZWixj3EzHBHVaQBw',
    appId: '1:934588973412:ios:203acf4537a2c83bc3ba71',
    messagingSenderId: '934588973412',
    projectId: 'match-a-muslim-978ca',
    storageBucket: 'match-a-muslim-978ca.appspot.com',
    iosClientId: '934588973412-39564tl0brc36s0eiqk1at8cv6qepd6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkcHhVVjyRA8LZc8RZWixj3EzHBHVaQBw',
    appId: '1:934588973412:ios:203acf4537a2c83bc3ba71',
    messagingSenderId: '934588973412',
    projectId: 'match-a-muslim-978ca',
    storageBucket: 'match-a-muslim-978ca.appspot.com',
    iosClientId: '934588973412-39564tl0brc36s0eiqk1at8cv6qepd6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingApp',
  );
}
